apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: dotnet-api-{{.Release.Name}}
  namespace: {{.Values.namepsace}}
spec:
  rules:
  - host: {{.Values.host}}
    http:
      paths:
      - backend:
          serviceName: dotnet-api-{{.Release.Name}}
          servicePort: 80
        path: /

