kind: Service
apiVersion: v1
metadata:
  name: dotnet-api-{{.Release.Name}}
  namespace: {{.Values.namepsace}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    io.godwit.service:  dotnet-api-{{.Release.Name}}
  type: ClusterIP
---